services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules # keep using node_modules of the container to avoid host OS malfunctions
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres:
    build: ./postgres
    env_file: ./postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
